let g:load_doxygen_syntax=1
set background=light
set backspace=indent,eol,start
set tabstop=4
set shiftwidth=4
set cino=(0
set formatoptions=cqa
set noincsearch
set nocompatible
set nobk
set writebackup
set nowrap
set expandtab
set hlsearch
set ruler
set number
set relativenumber
set wrap
set linebreak
set breakindent
set autoread
filetype plugin indent on
syntax enable
